/*

 http://www.JSON.org/json2.js
 2011-02-23

 Math.uuid.js (v1.4)
 http://www.broofa.com
 mailto:robert@broofa.com

 Copyright (c) 2010 Robert Kieffer
 Dual licensed under the MIT and GPL licenses.
*/
var n=void 0,JSON;JSON||(JSON={});
(function(){function i(a){return 10>a?"0"+a:a}function c(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var b=k[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function f(k,d){var l,h,e,i,o=a,m,j=d[k];j&&"object"===typeof j&&"function"===typeof j.toJSON&&(j=j.toJSON(k));"function"===typeof g&&(j=g.call(d,k,j));switch(typeof j){case "string":return c(j);case "number":return isFinite(j)?""+j:"null";case "boolean":case "null":return""+
j;case "object":if(!j)return"null";a+=b;m=[];if("[object Array]"===Object.prototype.toString.apply(j)){i=j.length;for(l=0;l<i;l+=1)m[l]=f(l,j)||"null";e=0===m.length?"[]":a?"[\n"+a+m.join(",\n"+a)+"\n"+o+"]":"["+m.join(",")+"]";a=o;return e}if(g&&"object"===typeof g){i=g.length;for(l=0;l<i;l+=1)"string"===typeof g[l]&&(h=g[l],(e=f(h,j))&&m.push(c(h)+(a?": ":":")+e))}else for(h in j)Object.prototype.hasOwnProperty.call(j,h)&&(e=f(h,j))&&m.push(c(h)+(a?": ":":")+e);e=0===m.length?"{}":a?"{\n"+a+m.join(",\n"+
a)+"\n"+o+"}":"{"+m.join(",")+"}";a=o;return e}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+i(this.getUTCMonth()+1)+"-"+i(this.getUTCDate())+"T"+i(this.getUTCHours())+":"+i(this.getUTCMinutes())+":"+i(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a,b,k={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;"function"!==typeof JSON.stringify&&(JSON.stringify=function(k,c,d){var h;b=a="";if("number"===typeof d)for(h=0;h<d;h+=1)b+=" ";else"string"===typeof d&&(b=d);if((g=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return f("",
{"":k})});"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function k(a,g){var c,d,e=a[g];if(e&&"object"===typeof e)for(c in e)Object.prototype.hasOwnProperty.call(e,c)&&(d=k(e,c),d!==n?e[c]=d:delete e[c]);return b.call(a,g,e)}var g,a=""+a;e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+a+")"),"function"===typeof b?k({"":g},""):g;throw new SyntaxError("JSON.parse");})})();
(function(){var i="0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z".split(",");Math.uuid=function(c,f){var e=[],d,f=f||i.length;if(c)for(d=0;d<c;d++)e[d]=i[0|Math.random()*f];else{var a;e[8]=e[13]=e[18]=e[23]="-";e[14]="4";for(d=0;36>d;d++)e[d]||(a=0|16*Math.random(),e[d]=i[19==d?a&3|8:a])}return e.join("")};Math.uuidFast=function(){for(var c=Array(36),f=0,e,d=0;36>d;d++)8==d||13==d||18==d||23==d?c[d]="-":14==d?c[d]="4":(2>=
f&&(f=33554432+16777216*Math.random()|0),e=f&15,f>>=4,c[d]=i[19==d?e&3|8:e]);return c.join("")};Math.uuidCompact=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var f=16*Math.random()|0;return("x"==c?f:f&3|8).toString(16)})}})();
(function(){function i(){}function c(a){this.p(a)}c.prototype.p=function(a){var b=a.location;this.url=b.href;this.hostname=b.hostname;this.protocol=b.protocol;var k=b.href.indexOf("#");this.hash=-1<k?b.href.substring(k):"";this.referrer=a.referrer;this.c=window.screen;a.documentElement!==n&&(this.documentElement=a.documentElement)};c.prototype.g=function(a){var b,k,g,c,d=0,e=0,h="",h=[];if(!a)return a;a=this.s(a+"");do b=a.charCodeAt(d++),k=a.charCodeAt(d++),g=a.charCodeAt(d++),c=b<<16|k<<8|g,b=c>>
18&63,k=c>>12&63,g=c>>6&63,c&=63,h[e++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c);while(d<a.length);h=h.join("");switch(a.length%3){case 1:h=h.slice(0,-2)+"==";break;case 2:h=h.slice(0,-1)+"="}return h};c.prototype.s=function(a){var a=
a+"",b="",c,g,d=0;c=g=0;for(var d=a.length,e=0;e<d;e++){var f=a.charCodeAt(e),h=null;128>f?g++:h=127<f&&2048>f?String.fromCharCode(f>>6|192)+String.fromCharCode(f&63|128):String.fromCharCode(f>>12|224)+String.fromCharCode(f>>6&63|128)+String.fromCharCode(f&63|128);null!==h&&(g>c&&(b+=a.substring(c,g)),b+=h,c=g=e+1)}g>c&&(b+=a.substring(c,a.length));return b};c.prototype.r=function(a,b){var c=new Date,d="_ZUID="+escape(a);c.setDate(c.getDate()+3650);d+=";expires="+c.toGMTString();document.cookie=d+
"; path=/"+(b?";domain=."+b:"")};c.prototype.a=function(a){var b;return 0<document.cookie.length&&(document.cookie.match("^"+a+"=")?b=0:(b=document.cookie.search("; "+a+"="),-1!==b&&(b+=2)),-1!==b)?(b=b+a.length+1,a=document.cookie.indexOf(";",b),-1===a&&(a=document.cookie.length),unescape(document.cookie.substring(b,a))):""};c.prototype.j=function(){return"string"===typeof window.ESTatTrackerCookieDomain&&0<window.ESTatTrackerCookieDomain.length?window.ESTatTrackerCookieDomain:/.*zum\.com$/.test(this.hostname)?
"zum.com":this.hostname};c.prototype.f=function(a,b){a.addEventListener?a.addEventListener("load",b,n):a.attachEvent&&a.attachEvent("onload",b)};c.prototype.m=function(){return parseInt((new Date).getTime().toString().substring(0,10),10)};c.prototype.o=function(){var a=sendData,b=[];if("object"===typeof a)for(var c in a)Object.hasOwnProperty.call(a,c)&&(b[b.length]=c+"="+a[c]);return b.join("&")};c.prototype.q=function(a,b){sendData={data:b};sendData.time=(new Date).getTime().toString();sendData=
this.o();"post"===a.toLowerCase()?this.e():2E3<sendData.length?this.e():this.k()};c.prototype.k=function(){sendURL="//estat.zum.com/at.gif?"+this.b(sendData);var a=new Image(1,1);a.src=sendURL;a.onload=function(){a.onload=null}};c.prototype.e=function(){var a=sendData,b=!1;try{var c=this,d=window.XMLHttpRequest?new window.XMLHttpRequest:null;d&&"withCredentials"in d?(d.open("POST","//estat.zum.com/collect",!0),d.setRequestHeader("Content-Type","text/plain;charset=UTF-8"),d.send(this.b(a))):window.XDomainRequest?
(d=new XDomainRequest,d.open("POST","//estat.zum.com/collect"),d.contentType="text/plain;charset=UTF-8",d.onload=function(){},d.onerror=function(){},d.ontimeout=function(){},d.onprogress=function(){},setTimeout(function(){d.send(c.b(a))},25)):b=!0;d.onreadystatechange=function(){4===this.readyState&&200!==this.status&&(b=!0)}}catch(e){b=!0}b&&this.d(this.b(a))};c.prototype.d=function(a){var b=this;if(document.body){try{var c=document.createElement('<iframe name="'+encodeURIComponent(a)+'"></iframe>')}catch(d){c=
document.createElement("iframe"),c.name=encodeURIComponent(a)}c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var e="//estat.zum.com/post_iframe.html#"+encodeURIComponent("http://"+location.host+"/favicon.ico");this.f(c,function(){setTimeout(function(){try{c.src="",c.parentNode&&c.parentNode.removeChild(c)}catch(a){}},300)});document.body.appendChild(c);c.src=e}else setTimeout(function(){b.d(a)},100)};c.prototype.b=function(a){var b=[];""!==this.a("_ZUID")&&(b[b.length]=
"_ZUID="+this.a("_ZUID"));""!==this.a("_UID3")&&(b[b.length]="_UID3="+this.a("_UID3"));return 0<b.length?a+"&"+b.join("&"):a};c.prototype.i=function(a,b){""===this.a("_ZUID")&&this.r(Math.uuid(),this.j());b=b||{};b.referrer===n&&(b.referrer=this.l());b.url===n&&(b.url=this.n());b.screenSize=this.c?this.c.width+"x"+this.c.height:"-";b.clientDocSize=this.documentElement?this.documentElement.clientWidth+"x"+this.documentElement.clientHeight:"-";b.time=this.m();b.version="A12";return this.g(JSON.stringify({event:a,
properties:b}))};c.prototype.n=function(){return"about:"===this.protocol?"http://zum.com/":this.url};c.prototype.l=function(){return"#smartzum"===this.hash?"about:smartzum":"about:"===this.protocol?this.url:this.referrer};c.prototype.isArray=function(a){return a&&"object"===typeof a&&"number"===typeof a.length&&"function"===typeof a.splice&&!a.propertyIsEnumerable("length")};c.prototype.h=function(a){a!==n&&"object"===typeof a&&delete a.ESTatTrackerPropHttpMethod};var f=new c(document);i.prototype.track=
function(a,b){if(a){var c="get";b!==n&&"object"===typeof b&&"ESTatTrackerPropHttpMethod"in b&&"string"===typeof b.ESTatTrackerPropHttpMethod&&(c=b.ESTatTrackerPropHttpMethod);f.h(b);var d=f.i(a,b);f.q(c,d)}};i.prototype.push=function(a){if(f.isArray(a))for(var b=0;b<a.length;++b)if(f.isArray(a[b]))this.track.apply(this,a[b]);else{this.track.apply(this,a);break}};i.prototype.getTrackerUtil=function(){return f};var e=window.ESTatTracker,d=new i;window.ESTatTracker=d;f.isArray(e)?d.push(e):("undefined"===
typeof window.ESTatTrackerPageView||!0===window.ESTatTrackerPageView)&&d.push(["@PageView"])})();
